name: Publish artefacts for release

on:
  push:
    tags:
      - '*'

jobs:
  publish-documentation:
    name: Publish documentation
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build documentation
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaHtml
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: build/dokka/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
  publish-maven-package:
    name: Publish Maven package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Publish Maven artifact
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}